config/routes.rb
Rails.application.routes.draw do
  
  get 'intervals/update'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/edit'
  get 'sessions/new'
  get 'users/new'

  root              'welcome#splash'
  get 'home'    =>  'static_pages#home'
  get 'help'    =>  'welcome#help'
  get 'about'   =>  'welcome#about'
  get 'contact' =>  'welcome#contact'
  get 'feed'    => 'static_pages#feed'
  get 'garage' => 'rides#garage'
  get 'parts' => 'static_pages#parts'
  get 'stats' => 'static_pages#stats'
  get 'add_vehicle' => 'vehicles#new'
  get 'vehicle_information' => 'vehicles#show'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'   =>  'sessions#create'
  delete 'logout'  =>  'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :rides do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  resources :vehicles do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
    has_many :intervals, as: :intervaled
    before_save :downcase_fields_and_upcase
    validates :make, :model, :category, presence: true
    validates :model, :make, :year, :category, :uniqueness => {:scope => [:make, :year, :category], message: "already exists"}
    validates :year, presence: true, numericality: true, :inclusion => { in: 1900..Date.today.year+1, message: "needs to be between 1900-#{Date.today.year+1}"}
    
    private
        
        def downcase_fields_and_upcase
          self.make = make.downcase.capitalize
          self.model = model.upcase
          self.category = category.split.map(&:capitalize).join(' ')
        end
    
    
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    
    before_action :logged_in_user
  
    def index
        @vehicles = Vehicle.all
    end
    
    def show
        @vehicle = Vehicle.find(params[:id])
        @intervals = @vehicle.intervals
    end
    
    def new
        @vehicle = Vehicle.new
    end
    
    def edit
        @vehicle = Vehicle.find(params[:id])
    end
 
    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            flash[:success] = "Vehicle Added!"
            redirect_to @vehicle
        else
            render 'new'
        end
    end
    
    def update
        @vehicle = Vehicle.find(params[:id])
        if @vehicle.update_attributes(vehicle_params)
              flash[:success] = "Vehicle Updated"
              redirect_to @vehicle
        else
          render 'edit'
        end
    end
    
    def destroy
        @vehicle = Vehicle.find(params[:id])
        @vehicle.destroy
        flash[:success] = "Vehicle removed"
        redirect_to vehicles_path
    end
    
    private
    
        def vehicle_params
            params.require(:vehicle).permit(:make, :model, :year, :category)
        end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :make %> 
<%= f.select(:make, options_for_select(['Beta', 'BMW','GasGas', 'Honda', 'Husqvarna', 'Kawasaki', 'KTM', 'Sherco', 'Suzuki', 'TM', 'Yamaha']), {}, {class: "form-control"}) %>

<%= f.label :model %>
<%= f.text_field :model, class: 'form-control' %>

<%= f.label :year %>
<%= f.text_field :year, class: 'form-control' %>

<%= f.label :category %>
<%= f.select(:category, options_for_select(['Dirt Bike', 'Street', 'Cruiser', 'UTV', 'ATV', 'Snowmobile']), {}, {class: "form-control"}) %>

app/views/vehicles/_intervals.html.erb
<div class="panel-group" id="intervals">
    <% @intervals.group_by{|l| l.group }.each do |group,intervals| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title"><a data-toggle="collapse" data-parent="#intervals" href="#<%= group %>"><%= group %></a></h4>
        </div>
        <div id="<%= group %>" class="panel-collapse collapse">
         <% intervals.each do |interval| %>
          <div id="<%= interval.id %>" class="panel-body">
            <%= interval.action %> <%= interval.description %> every <%= interval.length %> <%= interval.unit_of_measurement %>
            <span class="pull-right">
                <%= link_to "Edit", edit_vehicle_interval_path(@vehicle, interval), class:"btn btn-default" %>
                <a data-original-title="Edit This Interval" data-toggle="tooltip" type="button" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-time"></i></a
            </span>
          </div>
         <% end %>
        </div>
      </div>
    <% end %>
</div>

app/views/vehicles/edit.html.erb
<% provide(:title, "Edit Vehicle") %>
<div class="row">
<div class="col-lg-12">
    <h1 class="page-header">Update Vehicle</h1>
</div>
<!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@vehicle) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vehicles/index.html.erb
<% provide(:title, "OEM Vechicles") %>
<div class="row">
<div class="col-lg-12">
    <h1 class="page-header">OEM Vehicles</h1>
</div>
<!-- /.col-lg-12 -->
</div>

<row>
<div class="col-md-6">
      <%= link_to "Add OEM Vehicle", new_vehicle_path, class: "btn btn-primary" %>
</div>
</row>

  
<table id = "Vehicles" class="table table-striped table-bordered">
<thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Category</th>
    <th>Edit Vehicle</th>
    <th>See More</th>
  </tr>
</thead>
<tbody>
  <% @vehicles.each do |vehicle| %>
    <tr>
      <td><%= vehicle.make %></td>    
      <td><%= vehicle.model %></td>
      <td><%= vehicle.year %></td>
      <td><%= vehicle.category %></td>
      <td><%= link_to  "Edit", edit_vehicle_path(vehicle.id) %></td>
      <td><%= link_to  "Show", vehicle_path(vehicle.id) %></td>
    </tr>
  <% end %>
 </tbody>
</table>

app/views/vehicles/new.html.erb
<% provide(:title, 'Add Vehicle') %>
<div class="col-lg-12">
    <h1 class="page-header">New Vehicle</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@vehicle) do |f| %>
        <%= render 'fields', f: f %>
      <%= f.submit "Add Vehicle", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vehicles/show.html.erb
<% provide(:title, @vehicle.make) %>
<div class="col-lg-12">
    <h1 class="page-header"><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Category:</td>
                        <td><%= @vehicle.category %></td>
                      </tr>
                      <tr>
                        <td>Weight</td>
                        <td>250lbs</td>
                      </tr>
                      <tr>
                        <td>Horsepower</td>
                        <td>55</td>
                      </tr>
                      <tr>
                        <td>Rating</td>
                        <td>3.5/5</td>
                      </tr>
                        <tr>
                        <td>Description</td>
                        <td>Totally awesome dirtbike. Everyone should buy one.</td>
                      </tr>
                      <tr>
                        <td>Something</td>
                        <td>Tadah</td>
                      </tr>
                        <td>More Stuff</td>
                        <td>Figure this out later</td>
                      </tr>
                    </tbody>
                  </table>
                  
                  <a href="#" class="btn btn-primary">Read Reviews</a>
                  <a href="#" class="btn btn-primary">See More Information</a>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <%= link_to "Edit this Vehicle", edit_vehicle_path, :class => "btn btn-sm btn-warning" %>
                            <%= link_to "Delete this Vehicle", @vehicle, :class => "btn btn-sm btn-danger", method: :delete,
                                  data: { confirm: "You sure?" } %>
                        </span>
                 </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6">
            <div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">Intervals</a></li>
      <li><a href="#issues" data-toggle="tab">Issues</a></li>
      <li><a href="#modifications" data-toggle="tab">Modifications</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="home">
        
        </br>
          <% if @vehicle.intervals.count > 0 %>
            <%= render 'intervals' %>
          <% else %>
            No intervals found for this vehicle.  Click the 'New Interval' button to create a new interval.
          <% end %>
          </br>
        <%= link_to "New Interval", new_vehicle_interval_path(@vehicle), class: "btn btn-primary" %>
      </div>
      <div class="tab-pane fade" id="issues">
          <%= link_to "New Interval", new_vehicle_interval_path(@vehicle), class: "btn btn-primary" %>
      </div>
      <div class="tab-pane fade" id="modifications">
    	<form id="tab3">
        	<label>New Password</label>
        	<input type="password" class="input-xlarge">
        	<div>
        	    <button class="btn btn-primary">Update</button>
        	</div>
    	</form>
      </div>
  </div>
  </div>
          </div>
        </div>        
    </div>
</div>