config/routes.rb
Rails.application.routes.draw do
  
  get 'intervals/update'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/edit'
  get 'sessions/new'
  get 'users/new'

  root              'welcome#splash'
  get 'home'    =>  'static_pages#home'
  get 'help'    =>  'welcome#help'
  get 'about'   =>  'welcome#about'
  get 'contact' =>  'welcome#contact'
  get 'feed'    => 'static_pages#feed'
  get 'garage' => 'rides#garage'
  get 'parts' => 'static_pages#parts'
  get 'stats' => 'static_pages#stats'
  get 'add_vehicle' => 'vehicles#new'
  get 'vehicle_information' => 'vehicles#show'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'   =>  'sessions#create'
  delete 'logout'  =>  'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :rides do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  resources :vehicles do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  has_many :intervals, as: :intervaled
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, :make, :model, :category, :unit_of_measurement, presence: true
  validates :year, presence: true, numericality: true, :inclusion => { in: 1900..Date.today.year+1, message: "needs to be between 1900-#{Date.today.year+1}"}
  validate :picture_size
  


  private
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
    
    before_action :logged_in_user, only: [:garage, :new, :create, :edit, :update, :destroy]
    before_action :set_user
    before_action :correct_user, only: [:edit, :update]
    
    def garage
        @rides = @user.rides
    end

    def index
        @explores = Ride.where(is_private: false).paginate(page: params[:page], :per_page => 18)
        unless logged_in?
            render layout: "welcome"
        end
    end
    
    def show
        @ride = Ride.find(params[:id])
        @intervals = @ride.intervals
        unless logged_in?
            render layout: "welcome"
        end
    end
    
    def new
        @ride = Ride.new
    end

    def edit
        @ride = Ride.find(params[:id])
    end
    
    def create
        @ride = current_user.rides.build(ride_params)
        if @ride.save
            flash[:success] = "Ride Added!"
            redirect_to @ride
        else
            render 'new'
        end
    end

    def update
        @ride = Ride.find_by(id: params[:id])
        if @ride.update_attributes(editable_ride_params)
          flash[:success] = "Ride updated"
          redirect_to @ride
        else
          render 'edit'
        end
    end

    def destroy
        @ride = current_user.rides.find_by(id: params[:id])
        @ride.destroy
        flash[:success] = "Ride removed"
        redirect_to garage_url
    end
    
    private
    
        def correct_user
          @user = Ride.find(params[:id]).user
          redirect_to(root_url) unless current_user?(@user)
        end
        
        def set_user
            @user = current_user
        end
    
        def ride_params
            params.require(:ride).permit(:make, :model, :year, :name, :category, :unit_of_measurement, :picture, :is_private)
        end
        
        def editable_ride_params
            params.require(:ride).permit(:name, :picture, :is_private)
        end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_edit_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :make %>
<%= f.text_field :make, class: 'form-control', disabled: true %>

<%= f.label :model %>
<%= f.text_field :model, class: 'form-control', disabled: true %>

<%= f.label :year %>
<%= f.text_field :year, class: 'form-control', disabled: true %>

<%= f.label :name, "A Custom Name" %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :unit_of_measurement %>
<%= f.select(:unit_of_measurement, options_for_select(['Hours', 'Kilometers', 'Miles']), {}, {class: "form-control"}) %>

<%= f.label :category %>
<%= f.select(:category, options_for_select(['Dirt Bike', 'Street', 'Cruiser', 'UTV', 'ATV', 'Snowmobile']), {}, {class: "form-control"}) %>

<%= f.label "Make it private?" %> 
<%= f.check_box :is_private, {class: "form-control"} %></br>

app/views/rides/_explore.html.erb
<div class="col-sm-4 col-md-3 ">
 <div id="profile-widget" class="panel">
    <div class="panel-heading">
        <%= image_tag(explore.picture.url, class: "ride-image") if explore.picture? %>
    </div>
    <div class="panel-body">
       <div class="media">
          <a class="pull-left" href="#">
          <%= link_to gravatar_for(explore.user, size: 50), explore.user %>
          </a>
          <div class="media-body">
             <h2 class="media-heading"><%= explore.name %></h2>
             <%= explore.year %> <%= explore.make %> <%= explore.model %>
          </div>
       </div>
    </div>
    <div class="panel-footer">
       <div class="btn-group btn-group-justified">
          <%= link_to explore, :class => "btn btn-default" do %><i class="fa fa-eye"> 172</i><% end %>
          <a class="btn btn-default" role="button"><i class="fa fa-comment"></i> 34</a>
          <a class="btn btn-default" role="button"><i class="fa fa-heart"></i> 210</a>
       </div>
    </div>
 </div>
</div>

app/views/rides/_intervals.html.erb
<div class="panel-group" id="intervals">
    <% @intervals.group_by{|l| l.group }.each do |group,intervals| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title"><a data-toggle="collapse" data-parent="#intervals" href="#<%= group %>"><%= group %></a></h4>
        </div>
        <div id="<%= group %>" class="panel-collapse collapse">
         <% intervals.each do |interval| %>
          <div id="<%= interval.id %>" class="panel-body">
            <%= interval.action %> <%= interval.description %> every <%= interval.length %> <%= interval.unit_of_measurement %>
            <span class="pull-right">
                <%= link_to "Edit", edit_ride_interval_path(@ride, interval), class:"btn btn-default" %>
                <a data-original-title="Edit This Interval" data-toggle="tooltip" type="button" class="btn btn-sm btn-info"><i class="glyphicon glyphicon-time"></i></a
            </span>
          </div>
         <% end %>
        </div>
      </div>
    <% end %>
</div>

app/views/rides/_ride.html.erb
<div id="ride-<%= ride.id %>">  
<div class="col-lg-3 col-md-6">
      <div id="vehicle-widget" class="vehicle">
         <div class="vehicle-body">
            <%= image_tag(ride.picture.url, class: "img-circle img-responsive") if ride.picture? %>
         </div>
         <div class="vehicle-heading text-center">
            <h2 class="text-uppercase"><strong><%= ride.name %></strong></h2>
         </div>
         <div class="vehicle-heading text-center">
            <%= ride.make %> <%= ride.model %>
         </div>
         <div class="vehicle-footer">
            <div class="list-block">
               <ul class="text-center legend">
                  <li class="hours" style="margin-right: 1px;">
                     <div class="text-uppercase"><%= ride.unit_of_measurement %></div>
                     <h3><strong><%= time_ago_in_words(ride.created_at) %></strong></h3>
                  </li>
                  <li class="status">
                     STATUS 
                     <h3><i class="fa fa-thumbs-up fa-2x"></i></h3>
                  </li>
                  <li class="issues" style="margin-left: 1px;">
                     UPCOMING 
                     <h3><strong>10</strong></h3>
                  </li>
               </ul>
            </div>
            <div class="btn-group btn-group-justified text-uppercase text-center">
               <a class="btn btn-default" role="button"><i class="fa fa-cloud-upload fa-2x"></i><br><small>Update</small></a>
               <a class="btn btn-default" role="button"><i class="fa fa-share-alt fa-2x"></i><br><small>See Intervals</small></a>
               <!--<a class="btn btn-default" role="button"><i class="fa fa-history fa-2x"></i><br><small>Information</small></a>-->
               <%= link_to ride, :class => "btn btn-default" do %><i class="fa fa-history fa-2x"></i><br><small>Information</small><% end %>
            </div>
         </div>
      </div>
    </div>
</div>

app/views/rides/_ride_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name, "A Custom Name" %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :make %> 
<%= f.select(:make, options_for_select(['Beta', 'BMW', 'GasGas', 'Honda', 'Husqvarna', 'Kawasaki', 'KTM', 'Sherco', 'Suzuki', 'TM', 'Yamaha']), {}, {class: "form-control"}) %>

<%= f.label :model %>
<%= f.text_field :model, class: 'form-control' %>

<%= f.label :year %>
<%= f.number_field(:year, class: "form-control") %>

<%= f.label :unit_of_measurement %>
<%= f.select(:unit_of_measurement, options_for_select(['Hours', 'Kilometers', 'Miles']), {}, {class: "form-control"}) %>

<%= f.label :category %>
<%= f.select(:category, options_for_select(['Dirt Bike', 'Street', 'Cruiser', 'UTV', 'ATV', 'Snowmobile']), {}, {class: "form-control"}) %>

<%= f.label "Make it private?" %> 
<%= f.check_box :is_private, {class: "form-control"} %></br>

app/views/rides/edit.html.erb
<% provide(:title, "Edit Ride") %>
<h1>Update your Ride</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@ride) do |f| %>
      <%= render 'edit_fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#ride_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/rides/garage.html.erb
<% provide(:title, "My Garage") %>
<div class="col-lg-12">
    <h1 class="page-header">My Garage</h1>
</div>

<div class = "row">
 <%= render @rides %>
<div class="col-lg-3 col-md-6">
   <!--
      ****** CHART WIDGET *******
      -->    
   <div id="vehicle-widget" class="vehicle">
      <div class="vehicle-body">
         <%= image_tag("F800GSA.jpg", class: "vehicle-image") %>
      </div>
      <div class="vehicle-heading text-center">
         <h2 class="text-uppercase"><strong>BMW F800GSA</strong></h2>
      </div>
      <div class="vehicle-footer">
         <div class="list-block">
            <ul class="text-center legend">
               <li class="hours" style="margin-right: 1px;">
                  HOURS 
                  <h2>62</h2>
               </li>
               <li class="status">
                  STATUS 
                  <h2><i class="fa fa-thumbs-up fa-2x"></i></h2>
               </li>
               <li class="issues" style="margin-left: 1px;">
                  <5 HOURS  
                  <h2>10</h2>
               </li>
            </ul>
         </div>
         <div class="btn-group btn-group-justified text-uppercase text-center">
            <a class="btn btn-default" role="button"><i class="fa fa-cloud-upload fa-2x"></i><br><small>Update</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-share-alt fa-2x"></i><br><small>See Intervals</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-history fa-2x"></i><br><small>Information</small></a>
         </div>
      </div>
   </div>
</div>

<div class="col-lg-3 col-md-6">
   <!--
      ****** CHART WIDGET *******
      -->    
   <div id="vehicle-widget" class="vehicle">
      <div class="vehicle-body">
         <%= image_tag("GASGAS.jpg", class: "vehicle-image") %>
      </div>
      <div class="vehicle-heading text-center">
         <h2 class="text-uppercase"><strong>GASGAS TXT250</strong></h2>
      </div>
      <div class="vehicle-footer">
         <div class="list-block">
            <ul class="text-center legend">
               <li class="hours" style="margin-right: 1px;">
                  HOURS 
                  <h2>4</h2>
               </li>
               <li class="status">
                  STATUS 
                  <h2><i class="fa fa-thumbs-up fa-2x"></i></h2>
               </li>
               <li class="issues" style="margin-left: 1px;">
                  <5 HOURS  
                  <h2>4</h2>
               </li>
            </ul>
         </div>
         <div class="btn-group btn-group-justified text-uppercase text-center">
            <a class="btn btn-default" role="button"><i class="fa fa-cloud-upload fa-2x"></i><br><small>Update</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-share-alt fa-2x"></i><br><small>See Intervals</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-history fa-2x"></i><br><small>Information</small></a>
         </div>
      </div>
   </div>
</div>

<div class="col-lg-3 col-md-6">
   <!--
      ****** CHART WIDGET *******
      -->    
   <div id="vehicle-widget" class="vehicle">
      <div class="vehicle-body">
         <%= image_tag("yz250.jpg", class: "vehicle-image") %>
      </div>
      <div class="vehicle-heading text-center">
         <h2 class="text-uppercase"><strong>Yamaha YZ250</strong></h2>
      </div>
      <div class="vehicle-footer">
         <div class="list-block">
            <ul class="text-center legend">
               <li class="hours" style="margin-right: 1px;">
                  HOURS 
                  <h2>135</h2>
               </li>
               <li class="status">
                  STATUS 
                  <h2><i class="fa fa-thumbs-down fa-2x"></i></h2>
               </li>
               <li class="issues" style="margin-left: 1px;">
                  <5 HOURS  
                  <h2>43</h2>
               </li>
            </ul>
         </div>
         <div class="btn-group btn-group-justified text-uppercase text-center">
            <a class="btn btn-default" role="button"><i class="fa fa-cloud-upload fa-2x"></i><br><small>Update</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-share-alt fa-2x"></i><br><small>See Intervals</small></a>
            <a class="btn btn-default" role="button"><i class="fa fa-history fa-2x"></i><br><small>Information</small></a>
         </div>
      </div>
   </div>
</div>

<div class="col-lg-3 col-md-6">
   <!--
      ****** CHART WIDGET *******
      -->    
   <div id="vehicle-widget" class="vehicle">
      <div class="vehicle-body">
         <i class="fa fa-plus-square fa-5x vehicle-image"></i>
      </div>
      <div class="vehicle-heading text-center">
         <h2 class="text-uppercase"><strong>New Ride</strong></h2>
      </div>
      <div class="vehicle-footer">
         <%= link_to('Add Ride', new_ride_path, class: 'btn btn-primary btn-lg btn-block')  %>
      </div>
   </div>
</div>

   
</div>

app/views/rides/index.html.erb
<% provide(:title, "Explore Rides") %>
<div class="col-lg-12">
    <h1 class="page-header">Explore Rides</h1>
</div>

<% if @explores.any? %>
  <ul class="row">
    <%= render partial: "explore", collection: @explores %>
  </ul>
  <%= will_paginate @explores %>
<% end %>

app/views/rides/new.html.erb
<% provide(:title, 'Add A New Ride') %>
<div class="col-lg-12">
    <h1 class="page-header">Add A New Ride</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@ride, html: { multipart: true }) do |f| %>
        <%= render 'ride_fields', f: f %>
      <%= f.submit "Add Ride", class: "btn btn-primary" %>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#ride_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/rides/show.html.erb
<% provide(:title, @ride.name) %>
<div class="col-lg-12">
    <h1 class="page-header"><%= @ride.name %></h1>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-4">
                    <h2><%= @ride.name %></h2>
                    <p><strong>Owner: </strong> <%= link_to @ride.user.name, @ride.user %></p>
                    <p><strong>Make: </strong> <%= @ride.make %></p>
                    <p><strong>Model: </strong> <%= @ride.model %> </p>
                    <p><strong>Year: </strong> <%= @ride.year %> </p>
                    <p><strong>Category: </strong> <%= @ride.category %> </p>
                    <p><strong>Private? </strong> <%= @ride.is_private %> </p>
                </div>             
                <div class="col-xs-12 col-sm-8 text-center">
                    <figure>
                        <%= image_tag(@ride.picture.url, class:"img-circle img-responsive") if @ride.picture? %> 
                    </figure>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong> 20,7K </strong></h2>                    
                    <p><small><%= @ride.unit_of_measurement %></small></p>
                    <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>245</strong></h2>                    
                    <p><small>Following</small></p>
                    <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>43</strong></h2>                    
                    <p><small>Snippets</small></p>
                    <div class="btn-group dropup btn-block">
                      <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options </button>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu text-left" role="menu">
                        <li><a href="#"><span class="fa fa-envelope pull-right"></span><%= link_to "Settings", edit_ride_path %></a></li>
                        <li><a href="#"><span class="fa fa-list pull-right"></span><%= link_to "Delete", @ride, method: :delete, data: { confirm: "You sure?" } %></a></li>
                        <li class="divider"></li>
                        <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>
                      </ul>
                    </div>
                </div>
            </div>
    	 </div>                 
		</div>
<div class="col-md-6 col-lg-6">
    <div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">Intervals</a></li>
      <li><a href="#issues" data-toggle="tab">Issues</a></li>
      <li><a href="#modifications" data-toggle="tab">Modifications</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="home">
        </br>
          <% if @ride.intervals.count > 0 %>
            <%= render 'intervals' %>
          <% else %>
            No intervals found for this vehicle.  Click the 'New Interval' button to create a new interval.
          <% end %>
      </div>
      <div class="tab-pane fade" id="issues">
          <%= link_to "New Interval", new_ride_interval_path(@ride), class: "btn btn-primary" %>
      </div>
      <div class="tab-pane fade" id="modifications">
    	<form id="tab3">
        	<label>New Password</label>
        	<input type="password" class="input-xlarge">
        	<div>
        	    <button class="btn btn-primary">Update</button>
        	</div>
    	</form>
      </div>
  </div>
  </div>
	</div>
</div>
</div>