config/routes.rb
Rails.application.routes.draw do
  
  get 'intervals/update'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/edit'
  get 'sessions/new'
  get 'users/new'

  root              'welcome#splash'
  get 'home'    =>  'static_pages#home'
  get 'help'    =>  'welcome#help'
  get 'about'   =>  'welcome#about'
  get 'contact' =>  'welcome#contact'
  get 'feed'    => 'static_pages#feed'
  get 'garage' => 'rides#garage'
  get 'parts' => 'static_pages#parts'
  get 'stats' => 'static_pages#stats'
  get 'add_vehicle' => 'vehicles#new'
  get 'vehicle_information' => 'vehicles#show'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'   =>  'sessions#create'
  delete 'logout'  =>  'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :rides do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  resources :vehicles do
    resources :intervals, only: [:new, :create, :edit, :update]
  end
  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KOMBUSTION", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "KOMBUSTION", root_path, id: "logo" %>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-list fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li><%= link_to "Contact", contact_path %></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <% if logged_in? %>
                          <li><%= link_to "Users", users_path %></li>
                          <li><%= link_to current_user do %>
                                  <i class="fa fa-user fa-fw"></i> Profile
                              <% end %>
                          </li>
                          <li><%= link_to edit_user_path(current_user) do %>
                                  <i class="fa fa-gear fa-fw"></i> Settings
                              <% end %>
                          </li>
                          <li class="divider"></li>
                          <li><%= link_to logout_path, method: "delete" do %>
                                  <i class="fa fa-sign-in fa-fw"></i> Log out
                              <% end %>
                          </li>
                        <% else %>
                          <li><%= link_to login_path do %>
                                  <i class="fa fa-sign-in fa-fw"></i> Log in
                              <% end %>
                          </li>
                        <% end %>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
                <%= render 'layouts/sidebar' %>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <%= link_to root_path do %>
                  <i class="fa fa-dashboard fa-fw"></i> Dashboard
                <% end %>
            </li>
            <li>
                <%= link_to garage_path do %>
                  <i class="fa fa-car fa-fw"></i> My Garage
                <% end %>
            </li>
            <li>
                <%= link_to feed_path do %>
                  <i class="fa fa-comments fa-fw"></i> Social Feed
                <% end %>
            </li>
            <li>
                <%= link_to parts_path do %>
                  <i class="fa fa-database fa-fw"></i> Part Search
                <% end %>
            </li>
            <li>
                <%= link_to stats_path do %>
                  <i class="fa fa-area-chart fa-fw"></i> Statistics
                <% end %>
            </li>
            <li>
                <%= link_to stats_path do %>
                  <i class="fa fa-area-chart fa-fw"></i> Tips and Tricks
                <% end %>
            </li>
            <li>
                <%= link_to stats_path do %>
                  <i class="fa fa-area-chart fa-fw"></i> Kombustion Deals
                <% end %>
            </li>
            <li>
                <%= link_to rides_path do %>
                  <i class="fa fa-area-chart fa-fw"></i> Show and Tell
                <% end %>
            </li>
            <li>
                <%= link_to vehicles_path do %>
                  <i class="fa fa-area-chart fa-fw"></i> Vehicles
                <% end %>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

app/views/layouts/_welcome_footer.html.erb
<footer>
	<div class="sub-footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-md-6 col-lg-6">
				<ul class="social">
				  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
				  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
				  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
				  <li><a href="#"><i class="fa fa-youtube"></i></a></li>
			      <li><%= link_to "About",   about_path %></li>
			      <li><%= link_to "Contact", contact_path %></li>
			      <li><%= link_to "Help", help_path %></li>
			      <li><a href="http://janikknittle.com/">News</a></li>
			     </ul>
			
				<div class="wow fadeInLeft" data-wow-delay="0.1s">
				<div class="text-left">
				<p>&copy;Copyright 2015 - Kombustion. All rights reserved.</p>
				</div>
				
				</div>
			</div>
			<div class="col-sm-6 col-md-6 col-lg-6">
				<div class="wow fadeInRight" data-wow-delay="0.1s">
				<div class="text-right margintop-30">
					<p>Designed by <a href="http://janikknittle.com">Janik Knittle</a>.... with some help from <a href="http://bootstraptaste.com">Bootstraptaste</a></p>
				</div>
				</div>
			</div>
		</div>	
	</div>
	</div>
</footer>

app/views/layouts/_welcome_nav.html.erb
<nav class="navbar navbar-custom navbar-fixed-top transparent-nav" role="navigation">
    <div class="container navigation">
	
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <div class="navbar-brand"><%= link_to image_tag("kombustion.io.png", :alt => "Image Description", width:'150', height:'40' ), root_path %></div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
		  <ul class="nav navbar-nav">
			<li><div id="cart"></div></li>
			<li><%= link_to "HOME", root_path %></li>
			<li><%= link_to "EXPLORE", rides_path %></li>
			<li><%= link_to "LOGIN", login_path %></li>
		  </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
    <div id="wrapper">
    <%= render 'layouts/navbar' %>
      <div id="page-wrapper">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,600,700,800|Lato:100,400,300,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'welcome', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'welcome', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-custom">
      <div id="wrapper">
        <%= render 'layouts/welcome_nav' %>
        <div class="container extra-padding">
            <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
            <%= yield %>
        </div>
        <%= render 'layouts/welcome_footer' %>
      </div>
     <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
  </body>
</html>